export const accessoriesName = [
  {title:'PEHD'  ,route: null, disable:true},
  {title:'PHWD'  ,route: null, disable:true},
  {title:'HWD'   ,route: null, disable:true},
  {title:'EHD'   ,route: null, disable:true},
  {title:'CWD'   ,route: null, disable:true},
  {title:'AWP'   ,route: null, disable:true},
  {title:'DXD'   ,route: null, disable:true},
  {title:'DPVV2' ,route: null, disable:true},
  {title:'PCAP'  ,route: null, disable:true},
  {title:'PCAF'  ,route: null, disable:true},
  {title:'DPS'   ,route: null, disable:true},
  {title:'IN'    ,route: null, disable:true},
  {title:'OUT'   ,route: null, disable:true},
  {title:'EBPD2' ,route: null, disable:true},
  {title:'P1VOC' ,route: null, disable:true},
  {title:'SSR'   ,route: null, disable:true},
  {title:'P1RH'  ,route: null, disable:true},
  {title:'P2RH'  ,route: null, disable:true},
  {title:'EBPD'  ,route: null, disable:true},
  {title:'P1CO2' ,route: null, disable:true},
  {title:'P2CO2' ,route: null, disable:true},
  {title:'EXT1'  ,route: null, disable:true},
  {title:'EXT2'  ,route: null, disable:true},
  {title:'EXT3'  ,route: null, disable:true},
  {title:'EXT4'  ,route: null, disable:true},
  {title:'FLW1'  ,route: null, disable:true},
  {title:'FLW2'  ,route: null, disable:true},
  {title:'DSC'   ,route: null, disable:true},
  {title:'GLOBAL',route: null, disable:true},
  {title:'BPD'   ,route: null, disable:true},
  {title:'FKI'   ,route: null, disable:true},
  {title:'MBUS'  ,route: null, disable:true},
  ]