export const ImageSource = {
    filter: require("../assets/filter.png"),
    fire: require("../assets/fire.png"),
    heater: require("../assets/heater.png"),
    warning: require("../assets/warning.png"),
    check: require("../assets/check.png"),
    unCheck: require("../assets/unCheck.png"),
    star: require("../assets/star-icon.png"),
    arrow: require("../assets/arrow-up.png"),
    home: require("../assets/house.png"),
    home_in: require("../assets/house_in.png"),
    home_out: require("../assets/house_out.png"),
    info: require("../assets/info-icon.png"),
    setting: require("../assets/setting.png"),
    filter1: require("../assets/filter-1.png"), 
    arrowDown: require("../assets/arrow-down.png"),
    back: require("../assets/back.png"),
    lockOpen: require("../assets/lock-open.png"),
    callibration: require("../assets/callibration.png"),
    lock: require("../assets/lock.png"),
    sun: require("../assets/sun.png"),
    moon: require("../assets/moon.png"),
    snowflake: require("../assets/snowflake.png"),
    backArrow: require("../assets/backarrow.png"),
    HI: require('../assets/house-icon-original.png'),
    PI: require('../assets/sliders-icon-original.png'),
    II: require('../assets/info-icon-original.png'),
    SI: require('../assets/wrench-icon-original.png'),
    fan: require('../assets/fan.png'),
    wifiHigh: require('../assets/wifi-high.png'),
    wifiLow: require('../assets/wifi-low.png'),
    wifiMedium : require('../assets/wifi-medium.png'),
    wifiNone : require('../assets/wifi-none.png'),
}